# Generated by Django 4.1.2 on 2022-10-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_follower_followrequest_inbox_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comment_count',
            new_name='count',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
