# Generated by Django 4.1.2 on 2022-11-02 07:12

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_comment_contenttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='profile_url',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=backend.models.post_upload_to),
        ),
    ]
