# Generated by Django 4.1.2 on 2022-10-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_comment_contenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.TextField(default='[]', null=True),
        ),
    ]
