# Generated by Django 4.1.2 on 2022-11-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_author_profile_url_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default='No Title', max_length=255, null=True),
        ),
    ]
