# Generated by Django 4.1.2 on 2022-10-31 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(default='https://192.168.1.167:8000/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(blank=True, default='https://192.168.1.167:8000/', null=True),
        ),
    ]
