# Generated by Django 4.1.2 on 2022-10-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_post_origin_alter_post_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
