# Generated by Django 4.1.2 on 2022-11-05 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_post_title'),
        ('backend', '0010_alter_post_source'),
    ]

    operations = [
    ]
