# Generated by Django 4.1.2 on 2022-11-11 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_author_profileimage_alter_post_origin'),
        ('backend', '0012_alter_inbox_options_alter_author_profileimage_and_more'),
    ]

    operations = [
    ]
