# Generated by Django 4.1.2 on 2022-11-11 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_merge_20221110_1127'),
        ('backend', '0013_merge_20221111_0748'),
    ]

    operations = [
    ]
