# Generated by Django 4.1.2 on 2022-11-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_merge_20221111_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(blank=True, default='https://c404t3.herokuapp.com/', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(default='https://c404t3.herokuapp.com/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(blank=True, default='https://c404t3.herokuapp.com/', null=True),
        ),
    ]
