# Generated by Django 4.1.2 on 2022-11-12 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_inbox_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.post'),
        ),
        migrations.AlterField(
            model_name='like',
            name='object_id',
            field=models.URLField(null=True),
        ),
    ]
