# Generated by Django 4.1.2 on 2022-11-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_comment_post_alter_like_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='object_id',
            field=models.UUIDField(null=True),
        ),
    ]
