# Generated by Django 4.1.2 on 2022-11-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_like_object_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('host', models.URLField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('teamName', models.CharField(blank=True, max_length=100)),
                ('currentlyConnected', models.BooleanField(default=True)),
                ('requiresAuth', models.BooleanField(default=True)),
            ],
        ),
    ]
