# Generated by Django 4.1.2 on 2022-11-19 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_author_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.node'),
        ),
    ]
